---
- name: Install python & deps
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    update_cache: yes

- name: Install nano & vim & netcat on Flask server
  apt:
    name:
      - netcat-openbsd
      - nano
      - vim
    state: present

- name: Create virtualenv
  command: python3 -m venv /opt/flaskenv
  args:
    creates: /opt/flaskenv

- name: Install Flask
  command: /opt/flaskenv/bin/pip install flask