---
- name: Install python & deps
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - mariadb-client
      - libmariadb-dev
      - build-essential
    update_cache: yes

- name: Install nano & vim & netcat on Flask server
  apt:
    name:
      - netcat-openbsd
      - nano
      - vim
    state: present

- name: Create virtualenv
  command: python3 -m venv /opt/flaskenv
  args:
    creates: /opt/flaskenv

- name: Install Flask
  command: /opt/flaskenv/bin/pip install flask
  notify: Restart Flask

- name: Install MariaDB Python driver
  command: /opt/flaskenv/bin/pip install mariadb
  notify: Restart Flask

- name: Deploy Flask app from template
  template:
    src: app.py.j2
    dest: /root/app.py
  notify: Restart Flask

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/flask.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      User=root
      WorkingDirectory=/root
      ExecStart=/opt/flaskenv/bin/python /root/app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload systemd
    - Restart Flask

- name: Enable Flask
  systemd:
    name: flask
    enabled: yes
