- name: Install NGINX on Debian/Ubuntu
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_facts.pkg_mgr == "apt"

- name: Install NGINX on RedHat/Amazon Linux
  yum:
    name: nginx
    state: present
  when: ansible_facts.pkg_mgr == "yum" or ansible_facts.pkg_mgr == "dnf"

- name: Start and enable NGINX
  service:
    name: nginx
    state: started
    enabled: yes