---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Install nano & vim on nginx server
  yum:
    name:
      - nano
      - vim
    state: present

- name: Deploy nginx config from template
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Copy index.html & style.css to Nginx html directory
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - index.html
    - style.css    